services:
  # Frontend Service
  - type: web
    name: neurocal-frontend
    env: static
    rootDir: Neuro-Cal
    buildCommand: npm install --ignore-scripts && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://neurocal-backend.onrender.com
      - key: VITE_ANALYTICS_ENABLED
        value: true
      - key: VITE_STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false

  # Backend Service
  - type: web
    name: neurocal-backend
    env: node
    plan: free
    rootDir: Neuro-Cal
    buildCommand: npm install --ignore-scripts
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://neurocal-frontend.onrender.com
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false

databases:
  - name: neurocal-db
    databaseName: neurocal
    user: neurocal_user
    plan: free
